import { settlegrid } from "@settlegrid/mcp"
const sg = settlegrid.init({ toolSlug: "chinese-calendar", pricing: { defaultCostCents: 1, methods: { get_zodiac: { costCents: 1, displayName: "Get Chinese Zodiac" }, get_festival: { costCents: 1, displayName: "Get Festival" } } } })
const animals = ["Rat","Ox","Tiger","Rabbit","Dragon","Snake","Horse","Goat","Monkey","Rooster","Dog","Pig"]
const elements = ["Wood","Fire","Earth","Metal","Water"]
const getZodiac = sg.wrap(async (args: { year: number }) => { if (!args.year) throw new Error("year required"); const animal = animals[(args.year - 4) % 12]; const element = elements[Math.floor((args.year - 4) % 10 / 2)]; return { year: args.year, animal, element, full: `${element} ${animal}`, lucky_numbers: [Math.floor(Math.random() * 9) + 1, Math.floor(Math.random() * 9) + 1] } }, { method: "get_zodiac" })
const festivals = [ { name: "Chinese New Year (Spring Festival)", month: "Jan/Feb", duration: "15 days", description: "Biggest celebration, family reunions, red envelopes" }, { name: "Lantern Festival", month: "Feb/Mar", duration: "1 day", description: "End of New Year celebrations, lantern riddles" }, { name: "Qingming Festival", month: "Apr", duration: "1 day", description: "Tomb-sweeping day, honor ancestors" }, { name: "Dragon Boat Festival", month: "Jun", duration: "1 day", description: "Dragon boat races, zongzi (rice dumplings)" }, { name: "Mid-Autumn Festival", month: "Sep/Oct", duration: "1 day", description: "Moon viewing, mooncakes, family reunion" }, { name: "Double Ninth Festival", month: "Oct", duration: "1 day", description: "Climbing mountains, chrysanthemum wine" } ]
const getFestival = sg.wrap(async (args: { name?: string }) => { if (args.name) { const f = festivals.find(f => f.name.toLowerCase().includes(args.name!.toLowerCase())); if (!f) throw new Error("Festival not found"); return f }; return { count: festivals.length, festivals } }, { method: "get_festival" })
export { getZodiac, getFestival }
console.log("settlegrid-chinese-calendar MCP server ready | 1c/call | Powered by SettleGrid")
