/**
 * Auto-generated by scripts/template-of-the-week.ts.
 *
 * Each weekly run appends one entry: a static markdown import (so
 * webpack's asset/source rule inlines the body at build time) and a
 * BlogPost object with `published: false`. The founder reviews the
 * PR, rewrites the body, flips `published: true`, and merges.
 *
 * The script edits the regions delimited by the BEGIN/END comment
 * markers below. Do NOT remove the markers — the next run will lose
 * its insertion point and either error out or append at end of file.
 *
 * If you need to remove a draft (founder decided not to ship it):
 * delete the import line, the corresponding entry from TOTW_POSTS,
 * and the per-week markdown file under blog-bodies/totw/. The
 * history file at docs/content/totw-history.json is the
 * source-of-truth for "this was already featured" and stays.
 */
import type { BlogPost } from '../../blog-posts'

// TOTW_IMPORTS_BEGIN
// TOTW_IMPORTS_END

export const TOTW_POSTS: BlogPost[] = [
  // TOTW_ENTRIES_BEGIN
  // TOTW_ENTRIES_END
]
