import { settlegrid } from "@settlegrid/mcp"
const sg = settlegrid.init({ toolSlug: "name-generator", pricing: { defaultCostCents: 1, methods: { generate_name: { costCents: 1, displayName: "Generate Name" }, generate_username: { costCents: 1, displayName: "Generate Username" } } } })
const firstNames = { male: ["James","Oliver","William","Ethan","Liam","Noah","Lucas","Mason","Alexander","Benjamin","Daniel","Henry","Sebastian","Jack","Leo"], female: ["Emma","Olivia","Ava","Sophia","Isabella","Mia","Charlotte","Amelia","Harper","Evelyn","Luna","Aria","Chloe","Ella","Grace"] }
const lastNames = ["Smith","Johnson","Williams","Brown","Jones","Garcia","Miller","Davis","Wilson","Anderson","Taylor","Thomas","Moore","Jackson","Martin","Lee","White","Harris","Clark","Lewis"]
const generateName = sg.wrap(async (args: { gender?: string; count?: number }) => { const count = Math.min(args.count ?? 1, 20); const gender = args.gender?.toLowerCase() ?? (Math.random() > 0.5 ? "male" : "female"); const pool = firstNames[gender as keyof typeof firstNames] ?? firstNames.male; const names = Array.from({ length: count }, () => { const first = pool[Math.floor(Math.random() * pool.length)]; const last = lastNames[Math.floor(Math.random() * lastNames.length)]; return { first, last, full: `${first} ${last}` } }); return { count, gender, names } }, { method: "generate_name" })
const adjectives = ["swift","clever","mighty","silent","golden","cosmic","lunar","shadow","crystal","iron"]
const nouns = ["wolf","eagle","phoenix","dragon","falcon","tiger","raven","storm","blade","forge"]
const generateUsername = sg.wrap(async (args: { style?: string; count?: number }) => { const count = Math.min(args.count ?? 5, 20); const usernames = Array.from({ length: count }, () => { const adj = adjectives[Math.floor(Math.random() * adjectives.length)]; const noun = nouns[Math.floor(Math.random() * nouns.length)]; const num = Math.floor(Math.random() * 999); return `${adj}_${noun}${num}` }); return { count, usernames } }, { method: "generate_username" })
export { generateName, generateUsername }
console.log("settlegrid-name-generator MCP server ready | 1c/call | Powered by SettleGrid")
