import type { TransformOutput } from '../transforms/runner.js'

/**
 * Shape consumed by renderPrBody — a strict subset of OpenPrInput that
 * excludes the auth token and branch identifiers (neither of which
 * should appear in a human-readable PR description).
 */
export interface RenderPrBodyInput {
  repoOwner: string
  repoName: string
  changes: TransformOutput['changedFiles']
  dependencyBump: Record<string, string>
  envVarsRequired: string[]
}

/**
 * Generate the Markdown body for a SettleGrid-monetization pull
 * request. Pure function — same inputs always produce the same output,
 * so a single snapshot test covers the entire shape forever.
 *
 * The body is intentionally deterministic (no timestamps, no random
 * IDs) so reviewers can diff two runs and confirm the output is
 * reproducible. Token is NEVER accepted here; renderPrBody only
 * receives information that is already safe to publish in a public PR.
 */
export function renderPrBody(input: RenderPrBodyInput): string {
  const changeCount = input.changes.length
  const changeList =
    changeCount > 0
      ? input.changes.map((c) => `- \`${c.path}\``).join('\n')
      : '_(no files changed)_'

  const depEntries = Object.entries(input.dependencyBump)
  const depList =
    depEntries.length > 0
      ? depEntries.map(([name, range]) => `- \`${name}@${range}\``).join('\n')
      : '_(none)_'

  const envList =
    input.envVarsRequired.length > 0
      ? input.envVarsRequired.map((v) => `- \`${v}\``).join('\n')
      : '_(none)_'

  return `## SettleGrid monetization

This pull request was generated by \`npx settlegrid add\` against
\`${input.repoOwner}/${input.repoName}\`. It wraps the repo's handlers
with [SettleGrid](https://settlegrid.ai) so each invocation flows
through a per-call billing ledger — no proxy, no sidecar, no runtime
service dependency.

### Files changed (${changeCount})

${changeList}

### Dependencies added

${depList}

These land in \`dependencies\` of your \`package.json\`. Run
\`npm install\` (or \`pnpm install\` / \`yarn install\`) in the repo
root before merging so the lockfile is updated.

### Environment variables required

Set these in your deployment environment before the first wrapped
call is served — SettleGrid will otherwise reject requests with an
"API key missing" error:

${envList}

### How this works

- Each wrapped handler (MCP \`setRequestHandler\`, LangChain \`_call\` /
  \`invoke\`, or REST \`app.<verb>\`) is replaced with \`sg.wrap(handler,
  { method })\` which charges before delegating to the original.
- Pricing is configured in the \`settlegrid.init({ pricing })\` call
  inserted at the top of each wrapped file. Default is 1¢/call; add
  per-method overrides in the \`methods\` object (see the
  [pricing docs](https://settlegrid.ai/docs/pricing)).
- SettleGrid validates the caller's API key from request headers or
  MCP metadata. If no key is present, the call 402s before your
  handler runs, so you never serve unpaid traffic.

### How to remove SettleGrid

Revert this pull request with \`git revert\`, then run \`npm install\`
to drop \`@settlegrid/mcp\` from the lockfile. There are no database
migrations, no server-side state, and no vendor lock-in — reverting
this commit restores the exact original behavior byte-for-byte.

---

_Generated by \`npx settlegrid add\` · https://settlegrid.ai_
`
}
