#!/usr/bin/env npx tsx
/**
 * P5.1 — Funnel-analysis CLI for the day-60 memo.
 *
 * Runs the full funnel-queries module against PostHog and emits two
 * outputs: a JSON file of raw numbers (one per run), and a markdown
 * block printed to stdout that the founder pastes into
 * `docs/memos/funnel-analysis-day60.md` sections 1-4. Sections 5-6
 * (hypothesis comparison + Phase 5 recommendations) are founder rewrite
 * — this script does not generate them.
 *
 * ## Usage
 *
 *   POSTHOG_PERSONAL_API_KEY=phx_... \
 *   POSTHOG_PROJECT_ID=12345         \
 *     npx tsx scripts/funnel-analysis.ts [--days 30] [--out docs/memos/funnel-data-day60.json]
 *
 * Flags:
 *   --days N   Window size in days. Default 30.
 *   --out PATH Where to write the JSON output. Default
 *              `docs/memos/funnel-data-day60.json`.
 *   --quiet    Suppress the markdown stdout block; only write JSON.
 *
 * Exit codes:
 *   0 — success (data written + markdown emitted)
 *   1 — env vars missing or PostHog query failed
 *
 * The markdown block is intentionally terse and tabular. It's the
 * scaffolded data for sections 1-4 of the memo. Sections 5-6 of the
 * memo template carry founder-rewrite TODOs.
 */
import { writeFileSync, mkdirSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import {
  runFunnelQueries,
  FUNNEL_STAGES,
  type FunnelData,
} from '../apps/web/src/lib/funnel-queries.js'
import { EVENT_NAMES } from '../apps/web/src/lib/posthog.js'

interface CliArgs {
  days: number
  outPath: string
  quiet: boolean
}

function parseArgs(argv: string[]): CliArgs {
  const args: CliArgs = {
    days: 30,
    outPath: 'docs/memos/funnel-data-day60.json',
    quiet: false,
  }
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i]
    if (arg === '--days') {
      const next = argv[++i]
      const n = Number(next)
      if (!Number.isFinite(n) || n <= 0) {
        throw new Error(`--days requires a positive number, got ${next}`)
      }
      args.days = Math.floor(n)
    } else if (arg === '--out') {
      const next = argv[++i]
      if (!next) throw new Error('--out requires a path')
      args.outPath = next
    } else if (arg === '--quiet') {
      args.quiet = true
    } else if (arg === '-h' || arg === '--help') {
      // eslint-disable-next-line no-console
      console.log(USAGE)
      process.exit(0)
    } else {
      throw new Error(`Unknown argument: ${arg}`)
    }
  }
  return args
}

const USAGE = `Usage: funnel-analysis.ts [--days N] [--out PATH] [--quiet]

Required env:
  POSTHOG_PERSONAL_API_KEY  PostHog personal API key with project-read access
  POSTHOG_PROJECT_ID        Numeric project ID

Optional env:
  NEXT_PUBLIC_POSTHOG_HOST  Defaults to https://us.i.posthog.com
`

function fmtNum(n: number): string {
  return new Intl.NumberFormat('en-US').format(n)
}

function fmtPct(rate: number | null): string {
  return rate === null ? 'n/a' : `${(rate * 100).toFixed(1)}%`
}

function fmtMinutes(min: number | null): string {
  if (min === null || min <= 0) return 'n/a'
  if (min < 1) return `${(min * 60).toFixed(0)}s`
  if (min < 60) return `${min.toFixed(1)}m`
  if (min < 1440) return `${(min / 60).toFixed(1)}h`
  return `${(min / 1440).toFixed(1)}d`
}

function buildMarkdown(data: FunnelData): string {
  const lines: string[] = []
  lines.push(`<!-- Generated by scripts/funnel-analysis.ts at ${data.generatedAt} -->`)
  lines.push(``)
  lines.push(`## Section 1 — Raw event counts (${data.windowDays}-day window)`)
  lines.push(``)
  lines.push(`| Event | Total | Unique users | Active days | Min/day | Median/day | Max/day | Peak day |`)
  lines.push(`|---|---:|---:|---:|---:|---:|---:|---|`)
  for (const e of EVENT_NAMES) {
    const c = data.events[e]
    const stats = data.dailyStats[e]
    lines.push(
      `| \`${e}\` | ${fmtNum(c.total)} | ${fmtNum(c.unique)} | ${fmtNum(stats.activeDays)} | ${fmtNum(stats.minNonZero)} | ${fmtNum(Math.round(stats.median * 10) / 10)} | ${fmtNum(stats.max)} | ${stats.peakDay ?? 'n/a'} |`,
    )
  }
  lines.push(``)
  lines.push(
    `_Per-event daily breakdown: above table summarizes the daily distribution. Full per-day-per-event grid is in the JSON sidecar (\`daily\` array)._`,
  )
  lines.push(``)

  lines.push(`## Section 2 — Conversion rates between funnel stages`)
  lines.push(``)
  lines.push(`| From → To | From uniques | To uniques | Conversion rate | Median time-to-convert |`)
  lines.push(`|---|---:|---:|---:|---:|`)
  for (const c of data.conversions) {
    lines.push(
      `| \`${c.fromStage}\` → \`${c.toStage}\` | ${fmtNum(c.fromUniques)} | ${fmtNum(c.toUniques)} | ${fmtPct(c.rate)} | ${fmtMinutes(c.medianMinutesToConvert)} |`,
    )
  }
  lines.push(``)
  lines.push(
    `Funnel-stage uniques (any-time semantics — strict ordering is enforced only on time-to-convert):`,
  )
  lines.push(``)
  for (let i = 0; i < FUNNEL_STAGES.length; i++) {
    const stage = FUNNEL_STAGES[i]
    const uniques =
      i === 0
        ? data.events[stage]?.unique ?? 0
        : data.conversions.find((c) => c.toStage === stage)?.toUniques ?? 0
    lines.push(`- Stage ${i + 1} (\`${stage}\`): **${fmtNum(uniques)}** users`)
  }
  lines.push(``)

  lines.push(`## Section 3 — Dropoff diagnosis`)
  lines.push(``)
  lines.push(`Largest dropoffs (by absolute users lost, then by relative rate):`)
  lines.push(``)
  const dropoffs = [...data.conversions]
    .map((c) => ({
      ...c,
      absoluteLost: c.fromUniques - c.toUniques,
      relativeLossRate: c.rate === null ? null : 1 - c.rate,
    }))
    .sort((a, b) => b.absoluteLost - a.absoluteLost)
  for (const d of dropoffs) {
    lines.push(
      `- \`${d.fromStage}\` → \`${d.toStage}\`: lost **${fmtNum(d.absoluteLost)} users** (${d.relativeLossRate === null ? 'n/a' : fmtPct(d.relativeLossRate)} dropped). Median time-to-convert for those who did convert: ${fmtMinutes(d.medianMinutesToConvert)}.`,
    )
  }
  lines.push(``)
  lines.push(`Top error codes from \`scaffold_failed\`:`)
  lines.push(``)
  if (data.topErrors.length === 0) {
    lines.push(`- _(no scaffold failures in window)_`)
  } else {
    for (const e of data.topErrors) {
      lines.push(`- \`${e.code}\`: ${fmtNum(e.failures)} failures`)
    }
  }
  lines.push(``)

  lines.push(`## Section 4 — Anomalies (spikes, dips, timezone effects)`)
  lines.push(``)
  // ── Data-derived spikes ────────────────────────────────────────────
  lines.push(`**Spikes** — events whose peak day was disproportionately large (max-day / median-day ratio):`)
  lines.push(``)
  const spikes = (Object.entries(data.dailyStats) as Array<[
    string,
    typeof data.dailyStats[keyof typeof data.dailyStats],
  ]>)
    .filter(([, s]) => s.spikeRatio !== null && s.spikeRatio >= 2)
    .sort((a, b) => (b[1].spikeRatio ?? 0) - (a[1].spikeRatio ?? 0))
  if (spikes.length === 0) {
    lines.push(`- _(no events have a max-day-to-median-day ratio ≥ 2x)_`)
  } else {
    for (const [event, s] of spikes) {
      lines.push(
        `- \`${event}\`: ${fmtNum(s.max)} on ${s.peakDay} vs median ${fmtNum(Math.round(s.median * 10) / 10)} (${(s.spikeRatio ?? 0).toFixed(1)}x). Investigate the day's traffic source.`,
      )
    }
  }
  lines.push(``)

  // ── Dips ───────────────────────────────────────────────────────────
  lines.push(`**Dips** — events with low active-day coverage relative to window:`)
  lines.push(``)
  const dips = (Object.entries(data.dailyStats) as Array<[
    string,
    typeof data.dailyStats[keyof typeof data.dailyStats],
  ]>)
    .filter(([, s]) => s.total > 0 && s.activeDays < data.windowDays / 2)
    .sort((a, b) => a[1].activeDays - b[1].activeDays)
  if (dips.length === 0) {
    lines.push(`- _(no events with < 50% day coverage; activity is well-distributed)_`)
  } else {
    for (const [event, s] of dips) {
      lines.push(
        `- \`${event}\`: only ${s.activeDays} of ${data.windowDays} days had any events. Investigate downtime / outages / instrumentation gaps.`,
      )
    }
  }
  lines.push(``)

  // ── Timezone clustering ────────────────────────────────────────────
  lines.push(`**Timezone clustering** — hour-of-day distribution (UTC) for \`gallery_viewed\` (top of funnel):`)
  lines.push(``)
  if (data.hourClusters.length === 0) {
    lines.push(`- _(no \`gallery_viewed\` events in window)_`)
  } else {
    const totalHourly = data.hourClusters.reduce((a, b) => a + b.count, 0)
    const peakHour = data.hourClusters.reduce(
      (best, h) => (h.count > best.count ? h : best),
      data.hourClusters[0],
    )
    const peakShare = totalHourly > 0 ? peakHour.count / totalHourly : 0
    lines.push(
      `- Peak hour: **${peakHour.hourUtc.toString().padStart(2, '0')}:00 UTC** with ${fmtNum(peakHour.count)} events (${fmtPct(peakShare)} of total).`,
    )
    if (peakShare >= 0.2) {
      lines.push(
        `- Concentration ≥ 20% in a single hour suggests a dominant timezone. Cross-reference geo breakdown below to identify it.`,
      )
    } else {
      lines.push(`- Distribution is reasonably spread; no single timezone dominates.`)
    }
  }
  lines.push(``)

  // ── Top templates / geo (kept here as supporting context for anomaly review) ─
  lines.push(`**Top templates by \`scaffold_success\`:**`)
  lines.push(``)
  if (data.topTemplates.length === 0) {
    lines.push(`- _(no scaffold successes in window)_`)
  } else {
    for (const t of data.topTemplates) {
      lines.push(`- \`${t.slug}\`: ${fmtNum(t.successes)} successes`)
    }
  }
  lines.push(``)
  lines.push(`**Geographic breakdown (top countries by event volume):**`)
  lines.push(``)
  if (data.geoBreakdown.length === 0) {
    lines.push(`- _(no country-tagged events in window)_`)
  } else {
    for (const g of data.geoBreakdown) {
      lines.push(`- \`${g.country}\`: ${fmtNum(g.events)} events`)
    }
  }
  lines.push(``)

  lines.push(
    `<!-- Sections 5-6 (hypothesis comparison + recommendations) are founder rewrite. Do not generate these from data alone. -->`,
  )

  return lines.join('\n')
}

async function main(): Promise<number> {
  let cli: CliArgs
  try {
    cli = parseArgs(process.argv.slice(2))
  } catch (err) {
    // eslint-disable-next-line no-console
    console.error(err instanceof Error ? err.message : err)
    // eslint-disable-next-line no-console
    console.error(USAGE)
    return 1
  }

  let data: FunnelData | null
  try {
    data = await runFunnelQueries({ days: cli.days })
  } catch (err) {
    // eslint-disable-next-line no-console
    console.error(`PostHog query failed: ${err instanceof Error ? err.message : err}`)
    return 1
  }

  if (data === null) {
    // eslint-disable-next-line no-console
    console.error(
      'POSTHOG_PERSONAL_API_KEY and/or POSTHOG_PROJECT_ID are not set. ' +
        'See `--help` for required env. Exiting without writing.',
    )
    return 1
  }

  const outPath = resolve(process.cwd(), cli.outPath)
  mkdirSync(dirname(outPath), { recursive: true })
  writeFileSync(outPath, JSON.stringify(data, null, 2) + '\n', 'utf8')
  // eslint-disable-next-line no-console
  console.error(`✓ Wrote JSON: ${outPath}`)

  if (!cli.quiet) {
    // The markdown summary goes to stdout so the founder can pipe
    // (e.g. `... | pbcopy`) or redirect into the memo file.
    process.stdout.write(buildMarkdown(data) + '\n')
  }
  return 0
}

main().then(
  (code) => process.exit(code),
  (err) => {
    // eslint-disable-next-line no-console
    console.error(err)
    process.exit(1)
  },
)
