#!/usr/bin/env npx tsx
/**
 * P5.1 — Funnel-analysis CLI for the day-60 memo.
 *
 * Runs the full funnel-queries module against PostHog and emits two
 * outputs: a JSON file of raw numbers (one per run), and a markdown
 * block printed to stdout that the founder pastes into
 * `docs/memos/funnel-analysis-day60.md` sections 1-4. Sections 5-6
 * (hypothesis comparison + Phase 5 recommendations) are founder rewrite
 * — this script does not generate them.
 *
 * ## Usage
 *
 *   POSTHOG_PERSONAL_API_KEY=phx_... \
 *   POSTHOG_PROJECT_ID=12345         \
 *     npx tsx scripts/funnel-analysis.ts [--days 30] [--out docs/memos/funnel-data-day60.json]
 *
 * Flags:
 *   --days N   Window size in days. Default 30.
 *   --out PATH Where to write the JSON output. Default
 *              `docs/memos/funnel-data-day60.json`.
 *   --quiet    Suppress the markdown stdout block; only write JSON.
 *
 * Exit codes:
 *   0 — success (data written + markdown emitted)
 *   1 — env vars missing or PostHog query failed
 *
 * The markdown block is intentionally terse and tabular. It's the
 * scaffolded data for sections 1-4 of the memo. Sections 5-6 of the
 * memo template carry founder-rewrite TODOs.
 */
import { writeFileSync, mkdirSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import {
  runFunnelQueries,
  FUNNEL_STAGES,
  type FunnelData,
} from '../apps/web/src/lib/funnel-queries.js'
import { EVENT_NAMES } from '../apps/web/src/lib/posthog.js'

interface CliArgs {
  days: number
  outPath: string
  quiet: boolean
}

function parseArgs(argv: string[]): CliArgs {
  const args: CliArgs = {
    days: 30,
    outPath: 'docs/memos/funnel-data-day60.json',
    quiet: false,
  }
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i]
    if (arg === '--days') {
      const next = argv[++i]
      const n = Number(next)
      if (!Number.isFinite(n) || n <= 0) {
        throw new Error(`--days requires a positive number, got ${next}`)
      }
      args.days = Math.floor(n)
    } else if (arg === '--out') {
      const next = argv[++i]
      if (!next) throw new Error('--out requires a path')
      args.outPath = next
    } else if (arg === '--quiet') {
      args.quiet = true
    } else if (arg === '-h' || arg === '--help') {
      // eslint-disable-next-line no-console
      console.log(USAGE)
      process.exit(0)
    } else {
      throw new Error(`Unknown argument: ${arg}`)
    }
  }
  return args
}

const USAGE = `Usage: funnel-analysis.ts [--days N] [--out PATH] [--quiet]

Required env:
  POSTHOG_PERSONAL_API_KEY  PostHog personal API key with project-read access
  POSTHOG_PROJECT_ID        Numeric project ID

Optional env:
  NEXT_PUBLIC_POSTHOG_HOST  Defaults to https://us.i.posthog.com
`

function fmtNum(n: number): string {
  return new Intl.NumberFormat('en-US').format(n)
}

function fmtPct(rate: number | null): string {
  return rate === null ? 'n/a' : `${(rate * 100).toFixed(1)}%`
}

function fmtDuration(seconds: number | null): string {
  if (seconds === null || seconds <= 0) return 'n/a'
  if (seconds < 60) return `${Math.round(seconds)}s`
  if (seconds < 3600) return `${(seconds / 60).toFixed(1)}m`
  if (seconds < 86400) return `${(seconds / 3600).toFixed(1)}h`
  return `${(seconds / 86400).toFixed(1)}d`
}

function buildMarkdown(data: FunnelData): string {
  const lines: string[] = []
  lines.push(`<!-- Generated by scripts/funnel-analysis.ts at ${data.generatedAt} -->`)
  lines.push(``)
  lines.push(`## Section 1 — Raw event counts (${data.windowDays}-day window)`)
  lines.push(``)
  lines.push(`| Event | Total | Unique users |`)
  lines.push(`|---|---:|---:|`)
  for (const e of EVENT_NAMES) {
    const c = data.events[e]
    lines.push(`| \`${e}\` | ${fmtNum(c.total)} | ${fmtNum(c.unique)} |`)
  }
  lines.push(``)

  lines.push(`## Section 2 — Conversion rates between funnel stages`)
  lines.push(``)
  lines.push(`| From → To | From uniques | To uniques | Conversion rate | Median time-to-convert |`)
  lines.push(`|---|---:|---:|---:|---:|`)
  for (const c of data.conversions) {
    lines.push(
      `| \`${c.fromStage}\` → \`${c.toStage}\` | ${fmtNum(c.fromUniques)} | ${fmtNum(c.toUniques)} | ${fmtPct(c.rate)} | ${fmtDuration(c.medianSecondsToConvert)} |`,
    )
  }
  lines.push(``)
  lines.push(
    `Funnel-stage uniques (any-time semantics — strict ordering is enforced only on time-to-convert):`,
  )
  lines.push(``)
  for (let i = 0; i < FUNNEL_STAGES.length; i++) {
    const stage = FUNNEL_STAGES[i]
    const uniques =
      i === 0
        ? data.events[stage]?.unique ?? 0
        : data.conversions.find((c) => c.toStage === stage)?.toUniques ?? 0
    lines.push(`- Stage ${i + 1} (\`${stage}\`): **${fmtNum(uniques)}** users`)
  }
  lines.push(``)

  lines.push(`## Section 3 — Dropoff diagnosis`)
  lines.push(``)
  lines.push(`Largest dropoffs (by absolute users lost, then by relative rate):`)
  lines.push(``)
  const dropoffs = [...data.conversions]
    .map((c) => ({
      ...c,
      absoluteLost: c.fromUniques - c.toUniques,
      relativeLossRate: c.rate === null ? null : 1 - c.rate,
    }))
    .sort((a, b) => b.absoluteLost - a.absoluteLost)
  for (const d of dropoffs) {
    lines.push(
      `- \`${d.fromStage}\` → \`${d.toStage}\`: lost **${fmtNum(d.absoluteLost)} users** (${d.relativeLossRate === null ? 'n/a' : fmtPct(d.relativeLossRate)} dropped). Median time-to-convert for those who did convert: ${fmtDuration(d.medianSecondsToConvert)}.`,
    )
  }
  lines.push(``)
  lines.push(`Top error codes from \`scaffold_failed\`:`)
  lines.push(``)
  if (data.topErrors.length === 0) {
    lines.push(`- _(no scaffold failures in window)_`)
  } else {
    for (const e of data.topErrors) {
      lines.push(`- \`${e.code}\`: ${fmtNum(e.failures)} failures`)
    }
  }
  lines.push(``)

  lines.push(`## Section 4 — Anomalies (manual founder review)`)
  lines.push(``)
  lines.push(`Top templates by \`scaffold_success\`:`)
  lines.push(``)
  if (data.topTemplates.length === 0) {
    lines.push(`- _(no scaffold successes in window)_`)
  } else {
    for (const t of data.topTemplates) {
      lines.push(`- \`${t.slug}\`: ${fmtNum(t.successes)} successes`)
    }
  }
  lines.push(``)
  lines.push(`Geographic breakdown (top countries by event volume):`)
  lines.push(``)
  if (data.geoBreakdown.length === 0) {
    lines.push(`- _(no country-tagged events in window)_`)
  } else {
    for (const g of data.geoBreakdown) {
      lines.push(`- \`${g.country}\`: ${fmtNum(g.events)} events`)
    }
  }
  lines.push(``)
  lines.push(
    `**Founder review checklist (Section 4):** spikes/dips in daily counts (re-render the daily chart at \`/admin/funnel\` to eyeball), timezone clustering of events (US-day vs IST-day), correlation of error codes with specific templates.`,
  )
  lines.push(``)

  lines.push(
    `<!-- Sections 5-6 (hypothesis comparison + recommendations) are founder rewrite. Do not generate these from data alone. -->`,
  )

  return lines.join('\n')
}

async function main(): Promise<number> {
  let cli: CliArgs
  try {
    cli = parseArgs(process.argv.slice(2))
  } catch (err) {
    // eslint-disable-next-line no-console
    console.error(err instanceof Error ? err.message : err)
    // eslint-disable-next-line no-console
    console.error(USAGE)
    return 1
  }

  let data: FunnelData | null
  try {
    data = await runFunnelQueries({ days: cli.days })
  } catch (err) {
    // eslint-disable-next-line no-console
    console.error(`PostHog query failed: ${err instanceof Error ? err.message : err}`)
    return 1
  }

  if (data === null) {
    // eslint-disable-next-line no-console
    console.error(
      'POSTHOG_PERSONAL_API_KEY and/or POSTHOG_PROJECT_ID are not set. ' +
        'See `--help` for required env. Exiting without writing.',
    )
    return 1
  }

  const outPath = resolve(process.cwd(), cli.outPath)
  mkdirSync(dirname(outPath), { recursive: true })
  writeFileSync(outPath, JSON.stringify(data, null, 2) + '\n', 'utf8')
  // eslint-disable-next-line no-console
  console.error(`✓ Wrote JSON: ${outPath}`)

  if (!cli.quiet) {
    // The markdown summary goes to stdout so the founder can pipe
    // (e.g. `... | pbcopy`) or redirect into the memo file.
    process.stdout.write(buildMarkdown(data) + '\n')
  }
  return 0
}

main().then(
  (code) => process.exit(code),
  (err) => {
    // eslint-disable-next-line no-console
    console.error(err)
    process.exit(1)
  },
)
