#!/usr/bin/env bash
# Publishes templates from apps/web/public/registry.json to
# github.com/settlegrid as public MIT-licensed repos.
#
# Prereqs:
#   - settlegrid org exists on GitHub
#   - gh CLI authenticated with `repo` scope on an account that is a
#     member/admin of the settlegrid org
#   - Each open-source-servers/settlegrid-<slug>/ dir is scaffolded
#
# Idempotent: a repo that already exists on GitHub is left alone.
#
# Flags:
#   --dry-run        Print planned actions without touching anything
#   --limit N        Only publish the first N slugs (post-filter)
#   --only "<a,b>"   Only publish the named slugs (comma-separated)
#
# Examples:
#   scripts/publish-templates.sh --dry-run
#   scripts/publish-templates.sh --only airbyte,abstract-api,abuseipdb
#   scripts/publish-templates.sh --limit 3
#   scripts/publish-templates.sh                    # full bulk run

set -euo pipefail

REGISTRY=apps/web/public/registry.json
ROOT=open-source-servers
ORG=settlegrid

DRY_RUN=0
LIMIT=0
ONLY=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --dry-run) DRY_RUN=1; shift ;;
    --limit) LIMIT="$2"; shift 2 ;;
    --only) ONLY="$2"; shift 2 ;;
    *) echo "Unknown flag: $1" >&2; exit 2 ;;
  esac
done

if [[ ! -f "$REGISTRY" ]]; then
  echo "Registry not found at $REGISTRY" >&2; exit 1
fi

# Build slug list (filter by --only if given, then truncate by --limit)
ALL_SLUGS=$(node -e "console.log(require('./$REGISTRY').templates.map(t => t.slug).join('\n'))")

if [[ -n "$ONLY" ]]; then
  SLUGS=$(echo "$ALL_SLUGS" | grep -Fx -f <(echo "$ONLY" | tr ',' '\n') || true)
else
  SLUGS="$ALL_SLUGS"
fi

if [[ "$LIMIT" != "0" ]]; then
  SLUGS=$(echo "$SLUGS" | head -n "$LIMIT")
fi

TOTAL=$(echo "$SLUGS" | wc -l | tr -d ' ')
[[ -z "$SLUGS" ]] && { echo "No slugs to publish."; exit 0; }

echo "Publishing $TOTAL template(s) to $ORG org. dry-run=$DRY_RUN"
echo ""

N=0; PUBLISHED=0; SKIPPED=0; FAILED=0
FAILED_SLUGS=()

while read -r slug; do
  N=$((N+1))
  DIR="$ROOT/settlegrid-$slug"
  REPO="$ORG/settlegrid-$slug"
  TEMPLATE_JSON="$DIR/template.json"

  if [[ ! -d "$DIR" ]]; then
    echo "[$N/$TOTAL] $slug — local dir missing ($DIR), FAIL"
    FAILED=$((FAILED+1)); FAILED_SLUGS+=("$slug"); continue
  fi

  if gh repo view "$REPO" >/dev/null 2>&1; then
    echo "[$N/$TOTAL] $slug — already exists on GitHub, SKIP"
    SKIPPED=$((SKIPPED+1)); continue
  fi

  DESC="MCP server template — see https://settlegrid.ai/templates/$slug"
  if [[ -f "$TEMPLATE_JSON" ]]; then
    EXTRACTED=$(node -e "try { const t = require('./$TEMPLATE_JSON'); if (t.description) process.stdout.write(t.description) } catch (e) {}" 2>/dev/null || true)
    [[ -n "$EXTRACTED" ]] && DESC="$EXTRACTED"
  fi

  if [[ "$DRY_RUN" == "1" ]]; then
    echo "[$N/$TOTAL] $slug — DRY-RUN: would create $REPO with desc='$DESC' from $DIR"
    PUBLISHED=$((PUBLISHED+1)); continue
  fi

  pushd "$DIR" >/dev/null
  if [[ ! -d .git ]]; then
    git init -q -b main
    git add .
    git -c user.email='noreply@settlegrid.ai' -c user.name='SettleGrid Templater' \
        commit -qm "Initial commit — generated template scaffold

Generated by the SettleGrid Templater. See https://settlegrid.ai/templates/$slug
for usage, deploy buttons, and capability documentation." || {
      echo "[$N/$TOTAL] $slug — git commit FAILED"
      popd >/dev/null
      FAILED=$((FAILED+1)); FAILED_SLUGS+=("$slug"); continue
    }
  fi
  popd >/dev/null

  if gh repo create "$REPO" \
       --public \
       --description "$DESC" \
       --source "$DIR" \
       --push \
       --remote origin \
       >/dev/null 2>&1; then
    echo "[$N/$TOTAL] $slug — PUBLISHED ($REPO)"
    PUBLISHED=$((PUBLISHED+1))
  else
    echo "[$N/$TOTAL] $slug — gh repo create FAILED"
    FAILED=$((FAILED+1)); FAILED_SLUGS+=("$slug")
  fi

  # Brief pause every 10 repos to be polite to GitHub's API.
  if (( N % 10 == 0 )); then sleep 3; fi
done <<< "$SLUGS"

echo ""
echo "=== Summary ==="
echo "Total considered:           $TOTAL"
echo "Published:                  $PUBLISHED"
echo "Skipped (already on GitHub): $SKIPPED"
echo "Failed:                     $FAILED"
if (( FAILED > 0 )); then
  echo "Failed slugs:"
  for s in "${FAILED_SLUGS[@]}"; do echo "  - $s"; done
  exit 1
fi
