import { settlegrid } from "@settlegrid/mcp"
const sg = settlegrid.init({ toolSlug: "identity-faker", pricing: { defaultCostCents: 1, methods: { generate_identity: { costCents: 1, displayName: "Generate Fake Identity" }, generate_company: { costCents: 1, displayName: "Generate Fake Company" } } } })
const firstNames = ["Alex","Jordan","Morgan","Casey","Riley","Taylor","Quinn","Avery","Cameron","Dakota"]
const lastNames = ["Smith","Johnson","Williams","Brown","Jones","Davis","Wilson","Moore","Taylor","Anderson"]
const domains = ["example.com","test.org","demo.io","sample.dev","mock.net"]
const generateIdentity = sg.wrap(async (args: { count?: number }) => { const count = Math.min(args.count ?? 1, 10); const identities = Array.from({ length: count }, () => { const first = firstNames[Math.floor(Math.random() * firstNames.length)]; const last = lastNames[Math.floor(Math.random() * lastNames.length)]; const age = 18 + Math.floor(Math.random() * 62); const domain = domains[Math.floor(Math.random() * domains.length)]; return { name: `${first} ${last}`, email: `${first.toLowerCase()}.${last.toLowerCase()}@${domain}`, age, phone: `555-${String(Math.floor(Math.random() * 10000)).padStart(4, "0")}`, ssn_fake: `***-**-${String(Math.floor(Math.random() * 10000)).padStart(4, "0")}` } }); return { count, identities, warning: "FOR TESTING ONLY — not real identities" } }, { method: "generate_identity" })
const generateCompany = sg.wrap(async (args: { count?: number }) => { const prefixes = ["Global","Apex","Vertex","Nova","Quantum","Synergy","Pinnacle","Nexus"]; const suffixes = ["Solutions","Systems","Technologies","Industries","Dynamics","Corp","Labs","Group"]; const count = Math.min(args.count ?? 1, 10); const companies = Array.from({ length: count }, () => { const name = `${prefixes[Math.floor(Math.random() * prefixes.length)]} ${suffixes[Math.floor(Math.random() * suffixes.length)]}`; return { name, domain: name.toLowerCase().replace(/ /g, "") + ".com", ein_fake: `XX-${String(Math.floor(Math.random() * 10000000)).padStart(7, "0")}`, founded: 1990 + Math.floor(Math.random() * 34), employees: Math.floor(Math.random() * 10000) + 10 } }); return { count, companies, warning: "FOR TESTING ONLY" } }, { method: "generate_company" })
export { generateIdentity, generateCompany }
console.log("settlegrid-identity-faker MCP server ready | 1c/call | Powered by SettleGrid")
