/**
 * P5.1 — Pure formatters + markdown builder for the funnel-analysis
 * memo output.
 *
 * Lives under `apps/web/src/lib/` (not in `scripts/`) so the same
 * formatters can be tested by the web app's vitest runner and reused
 * by other surfaces if needed (e.g. an admin "export memo" button on
 * the dashboard). The CLI script at `scripts/funnel-analysis.ts`
 * imports from this module.
 *
 * All exports are pure (no I/O, no module-level side effects). Tests
 * live at `__tests__/funnel-markdown.test.ts`.
 */
import { EVENT_NAMES } from './posthog'
import {
  FUNNEL_STAGES,
  type FunnelData,
} from './funnel-queries'

// ─── Pure formatters ────────────────────────────────────────────────────────

/** Locale-formatted integer. `1234` → `"1,234"`. NaN-safe. */
export function fmtNum(n: number): string {
  if (!Number.isFinite(n)) return '0'
  return new Intl.NumberFormat('en-US').format(n)
}

/** Rate as percent with 1 decimal. `null` → `"n/a"`. */
export function fmtPct(rate: number | null): string {
  if (rate === null || !Number.isFinite(rate)) return 'n/a'
  return `${(rate * 100).toFixed(1)}%`
}

/**
 * Minute-denominated duration → human-readable string.
 *
 * Branch table:
 *   - `null` or `<= 0`           → `"n/a"`
 *   - `min < 1`                  → `"<seconds>s"` (e.g. `0.025` → `"2s"`)
 *   - `1 <= min < 60`            → `"<min>m"`     (e.g. `5.5` → `"5.5m"`)
 *   - `60 <= min < 1440`         → `"<hours>h"`   (e.g. `90` → `"1.5h"`)
 *   - `min >= 1440`              → `"<days>d"`    (e.g. `2880` → `"2.0d"`)
 *
 * The "<= 0" guard collapses both genuine "no users converted" (null at
 * the storage layer) and degenerate zero-second medians into the same
 * "n/a" display, which is what the spec wants — both are "no signal."
 */
export function fmtMinutes(min: number | null): string {
  if (min === null || !Number.isFinite(min) || min <= 0) return 'n/a'
  if (min < 1) return `${(min * 60).toFixed(0)}s`
  if (min < 60) return `${min.toFixed(1)}m`
  if (min < 1440) return `${(min / 60).toFixed(1)}h`
  return `${(min / 1440).toFixed(1)}d`
}

// ─── Markdown builder ───────────────────────────────────────────────────────

/**
 * Render the funnel-analysis memo's data sections (1-4) as markdown.
 *
 * The output is self-contained — it includes its own `## Section 1`
 * through `## Section 4` headers. The memo template at
 * `docs/memos/funnel-analysis-day60.md` wraps this between
 * `<!-- BEGIN SCRIPT OUTPUT -->` markers; the founder pastes the
 * stdout output between them, replacing the placeholder.
 *
 * Sections 5-6 (hypothesis + recommendations) are founder rewrite —
 * not generated here.
 */
export function buildMarkdown(data: FunnelData): string {
  const lines: string[] = []
  lines.push(`<!-- Generated by scripts/funnel-analysis.ts at ${data.generatedAt} -->`)
  lines.push(``)
  lines.push(`## Section 1 — Raw event counts (${data.windowDays}-day window)`)
  lines.push(``)
  lines.push(`| Event | Total | Unique users | Active days | Min/day | Median/day | Max/day | Peak day |`)
  lines.push(`|---|---:|---:|---:|---:|---:|---:|---|`)
  for (const e of EVENT_NAMES) {
    const c = data.events[e]
    const stats = data.dailyStats[e]
    lines.push(
      `| \`${e}\` | ${fmtNum(c.total)} | ${fmtNum(c.unique)} | ${fmtNum(stats.activeDays)} | ${fmtNum(stats.minNonZero)} | ${fmtNum(Math.round(stats.median * 10) / 10)} | ${fmtNum(stats.max)} | ${stats.peakDay ?? 'n/a'} |`,
    )
  }
  lines.push(``)
  lines.push(
    `_Per-event daily breakdown: above table summarizes the daily distribution. Full per-day-per-event grid is in the JSON sidecar (\`daily\` array)._`,
  )
  lines.push(``)

  lines.push(`## Section 2 — Conversion rates between funnel stages`)
  lines.push(``)
  lines.push(`| From → To | From uniques | To uniques | Conversion rate | Median time-to-convert |`)
  lines.push(`|---|---:|---:|---:|---:|`)
  for (const c of data.conversions) {
    lines.push(
      `| \`${c.fromStage}\` → \`${c.toStage}\` | ${fmtNum(c.fromUniques)} | ${fmtNum(c.toUniques)} | ${fmtPct(c.rate)} | ${fmtMinutes(c.medianMinutesToConvert)} |`,
    )
  }
  lines.push(``)
  lines.push(
    `Funnel-stage uniques (any-time semantics — strict ordering is enforced only on time-to-convert):`,
  )
  lines.push(``)
  for (let i = 0; i < FUNNEL_STAGES.length; i++) {
    const stage = FUNNEL_STAGES[i]
    const uniques =
      i === 0
        ? data.events[stage]?.unique ?? 0
        : data.conversions.find((c) => c.toStage === stage)?.toUniques ?? 0
    lines.push(`- Stage ${i + 1} (\`${stage}\`): **${fmtNum(uniques)}** users`)
  }
  lines.push(``)

  lines.push(`## Section 3 — Dropoff diagnosis`)
  lines.push(``)
  lines.push(`Largest dropoffs (by absolute users lost, then by relative rate):`)
  lines.push(``)
  const dropoffs = [...data.conversions]
    .map((c) => ({
      ...c,
      absoluteLost: c.fromUniques - c.toUniques,
      relativeLossRate: c.rate === null ? null : 1 - c.rate,
    }))
    .sort((a, b) => b.absoluteLost - a.absoluteLost)
  for (const d of dropoffs) {
    lines.push(
      `- \`${d.fromStage}\` → \`${d.toStage}\`: lost **${fmtNum(d.absoluteLost)} users** (${d.relativeLossRate === null ? 'n/a' : fmtPct(d.relativeLossRate)} dropped). Median time-to-convert for those who did convert: ${fmtMinutes(d.medianMinutesToConvert)}.`,
    )
  }
  lines.push(``)
  lines.push(`Top error codes from \`scaffold_failed\`:`)
  lines.push(``)
  if (data.topErrors.length === 0) {
    lines.push(`- _(no scaffold failures in window)_`)
  } else {
    for (const e of data.topErrors) {
      lines.push(`- \`${e.code}\`: ${fmtNum(e.failures)} failures`)
    }
  }
  lines.push(``)

  lines.push(`## Section 4 — Anomalies (spikes, dips, timezone effects)`)
  lines.push(``)
  // ── Data-derived spikes ────────────────────────────────────────────
  lines.push(`**Spikes** — events whose peak day was disproportionately large (max-day / median-day ratio):`)
  lines.push(``)
  const spikes = (Object.entries(data.dailyStats) as Array<[
    string,
    typeof data.dailyStats[keyof typeof data.dailyStats],
  ]>)
    .filter(([, s]) => s.spikeRatio !== null && s.spikeRatio >= 2)
    .sort((a, b) => (b[1].spikeRatio ?? 0) - (a[1].spikeRatio ?? 0))
  if (spikes.length === 0) {
    lines.push(`- _(no events have a max-day-to-median-day ratio ≥ 2x)_`)
  } else {
    for (const [event, s] of spikes) {
      lines.push(
        `- \`${event}\`: ${fmtNum(s.max)} on ${s.peakDay} vs median ${fmtNum(Math.round(s.median * 10) / 10)} (${(s.spikeRatio ?? 0).toFixed(1)}x). Investigate the day's traffic source.`,
      )
    }
  }
  lines.push(``)

  // ── Dips ───────────────────────────────────────────────────────────
  lines.push(`**Dips** — events with low active-day coverage relative to window:`)
  lines.push(``)
  const dips = (Object.entries(data.dailyStats) as Array<[
    string,
    typeof data.dailyStats[keyof typeof data.dailyStats],
  ]>)
    .filter(([, s]) => s.total > 0 && s.activeDays < data.windowDays / 2)
    .sort((a, b) => a[1].activeDays - b[1].activeDays)
  if (dips.length === 0) {
    lines.push(`- _(no events with < 50% day coverage; activity is well-distributed)_`)
  } else {
    for (const [event, s] of dips) {
      lines.push(
        `- \`${event}\`: only ${s.activeDays} of ${data.windowDays} days had any events. Investigate downtime / outages / instrumentation gaps.`,
      )
    }
  }
  lines.push(``)

  // ── Timezone clustering ────────────────────────────────────────────
  lines.push(`**Timezone clustering** — hour-of-day distribution (UTC) for \`gallery_viewed\` (top of funnel):`)
  lines.push(``)
  if (data.hourClusters.length === 0) {
    lines.push(`- _(no \`gallery_viewed\` events in window)_`)
  } else {
    const totalHourly = data.hourClusters.reduce((a, b) => a + b.count, 0)
    const peakHour = data.hourClusters.reduce(
      (best, h) => (h.count > best.count ? h : best),
      data.hourClusters[0],
    )
    const peakShare = totalHourly > 0 ? peakHour.count / totalHourly : 0
    lines.push(
      `- Peak hour: **${peakHour.hourUtc.toString().padStart(2, '0')}:00 UTC** with ${fmtNum(peakHour.count)} events (${fmtPct(peakShare)} of total).`,
    )
    if (peakShare >= 0.2) {
      lines.push(
        `- Concentration ≥ 20% in a single hour suggests a dominant timezone. Cross-reference geo breakdown below to identify it.`,
      )
    } else {
      lines.push(`- Distribution is reasonably spread; no single timezone dominates.`)
    }
  }
  lines.push(``)

  // ── Top templates / geo (kept here as supporting context for anomaly review) ─
  lines.push(`**Top templates by \`scaffold_success\`:**`)
  lines.push(``)
  if (data.topTemplates.length === 0) {
    lines.push(`- _(no scaffold successes in window)_`)
  } else {
    for (const t of data.topTemplates) {
      lines.push(`- \`${t.slug}\`: ${fmtNum(t.successes)} successes`)
    }
  }
  lines.push(``)
  lines.push(`**Geographic breakdown (top countries by event volume):**`)
  lines.push(``)
  if (data.geoBreakdown.length === 0) {
    lines.push(`- _(no country-tagged events in window)_`)
  } else {
    for (const g of data.geoBreakdown) {
      lines.push(`- \`${g.country}\`: ${fmtNum(g.events)} events`)
    }
  }
  lines.push(``)

  lines.push(
    `<!-- Sections 5-6 (hypothesis comparison + recommendations) are founder rewrite. Do not generate these from data alone. -->`,
  )

  return lines.join('\n')
}
